apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craque-fc.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "craque-fc.labels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.api.port | quote }}
  {{- if .Values.dragonfly.enabled }}
  DRAGONFLY_HOST: {{ include "craque-fc.fullname" . }}-dragonfly
  DRAGONFLY_PORT: {{ .Values.dragonfly.port | quote }}
  {{- end }}
