apiVersion: v1
kind: Secret
metadata:
  name: {{ include "craque-fc.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "craque-fc.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data: {}
