apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craque-fc.fullname" . }}-web
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "craque-fc.labels" . | nindent 4 }}
    {{- include "craque-fc.web.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "craque-fc.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "craque-fc.labels" . | nindent 8 }}
        {{- include "craque-fc.web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "craque-fc.image" (dict "global" .Values.global "image" .Values.web.image) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
