global:
  imageRegistry: ghcr.io

api:
  image:
    repository: craque-fc/api
    tag: staging
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: false

web:
  image:
    repository: craque-fc/web
    tag: staging
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false

worker:
  image:
    repository: craque-fc/worker
    tag: staging
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

dragonfly:
  enabled: true
  image:
    repository: docker.dragonflydb.io/dragonflydb/dragonfly
    tag: latest
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

migrations:
  image:
    repository: craque-fc/api
    tag: staging

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: staging.craquefc.app
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: web
  tls:
    - secretName: craque-fc-staging-tls
      hosts:
        - staging.craquefc.app
